name: Build every F* version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        run: |
          echo "matrix=$(jq -c '{include: [.[] | select(.broken? | not) | {version: .version, name: .name}]}' < ./versions.json)" >> $GITHUB_OUTPUT

  build:
    needs: configure
    name: F* ${{ matrix.fstar.version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fstar: ${{ fromJson(needs.configure.outputs.matrix).include }}
        os: [ubuntu-latest, macos-latest]
        # Some version of F* cannot be built under MacOS, skip them.
        exclude:
        - os: macos-latest
          fstar:
            name: v2025_06_13
        - os: macos-latest
          fstar:
            name: v2025_06_20
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: fstar-nix-versions
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          VERSION=${{ matrix.fstar.name }}
          echo "VERSION=$VERSION"
          VERSION="${VERSION//./_}"
          echo "VERSION=$VERSION"
          nix build .#"fstar_$VERSION"

  matrix-status:
    needs: build
    runs-on: ubuntu-latest
    if: success()  # Only runs if all matrix jobs pass
    steps:
      - name: Confirm matrix success
        run: echo "All matrix builds succeeded."
