name: Nightly Script Runner

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-nightly-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add new F* versions
        run: |
          bash ./update.sh

      - name: Commit changes (if any)
        run: |
          git diff --quiet || (
            BRANCH=nightly-update-${{ github.run_id }}
            git add .
            git commit -m "Nightly update on $(date -u +"%Y-%m-%d")"
          )

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GH_PAT }}
          title: "Nightly update - ${{ github.run_id }}"
          body: "Automated nightly update generated by GitHub Actions."

      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
